const FETCH_USERS: string = 'FETCH_USERS'
const FETCH_USERS_COMPLETED: string = 'FETCH_USERS_COMPLETED'
const FETCH_USERS_FAILED: string = 'FETCH_USERS_FAILED'

const FETCH_ADMINS: string = 'FETCH_ADMINS'
const FETCH_ADMINS_COMPLETED: string = 'FETCH_ADMINS_COMPLETED'
const FETCH_ADMINS_FAILED: string = 'FETCH_ADMINS_FAILED'

export default {
    FETCH_USERS,
    FETCH_USERS_COMPLETED,
    FETCH_USERS_FAILED,
    FETCH_ADMINS,
    FETCH_ADMINS_COMPLETED,
    FETCH_ADMINS_FAILED
}